# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cancer and the DNA
email: shubhamagarwal1993@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Identify signs of cancer with blood sample.
  Identify a unique cell by an electric pulse.
  Send electric pulse to kill the cell.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  shubhamagarwal1993

# Build settings
markdown: kramdown
